/*
 * File: app/view/Home/index.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Home.index', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.homeindex',

    requires: [
        'TabUserInformation.view.Home.indexViewModel',
        'TabUserInformation.view.Home.indexViewController',
        'TabUserInformation.view.Home.MainTab',
        'Ext.tab.Panel'
    ],

    controller: 'homeindex',
    
    viewModel: {
        type: 'homeindex'
    },

    //bind: {
    //    store: '{userinfoStore}'
    //},

    id: 'myviewport',
    itemId: 'myviewport',
    padding: 5,
    layout: 'border',

    items: [
//        {
//            xtype: 'container',
//            region: 'north',
//            height: 66,
//            layout: {
//                type: 'hbox',
//                align: 'middle',
//                pack: 'end'
//            },
//            items: [
//                {
//                    xtype: 'container',
//                    layout: {
//                        type: 'table',
//                        columns: 1
//                    },
//                    margin: '0 20 0 0',
//                    items: [
//                        {
//                            xtype: 'container',
//                            layout: {
//                                type: 'hbox',
//                                pack: 'end'
//                            },
//                            width: 200,
//                            items: [
//                                {
//                                    xtype: 'button',
//                                    glyph: 'xf08b@FontAwesome',
//                                    iconAlign: 'right',
//                                    text: 'Logout',
//                                    listeners: {
//                                        click: 'onButtonLogoutClick'
//                                    }
//                                }
//                            ]
//                        },
//                        {
//                            xtype: 'label',
//                            bind: {
//                                html: '<span style="color:white"><b>{FullNameTh} <br/> {DeptThaiDesc}</b></span>'
//                            }
//                        }
//                    ]
//                }
//            ]
//        },
        {
            xtype: 'homemaintab',
            region: 'center'
        }
    ],

    listeners: {
        beforerender: 'onMainViewBeforeRender',
        scope: 'controller'
    }

});