/*
 * File: app/view/Home/index.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Home.index', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.homeindex',

    requires: [
        'TabUserInformation.view.Home.indexViewModel',
        'TabUserInformation.view.Home.indexViewController',
        'TabUserInformation.view.Home.MainTab',
        'Ext.tab.Panel'
    ],

    controller: 'homeindex',
    
    viewModel: {
        type: 'homeindex'
    },

    //bind: {
    //    store: '{userinfoStore}'
    //},

    id: 'myviewport',
    itemId: 'myviewport',
    padding: 5,

    items: [
        {
            xtype: 'homemaintab'//,
            //padding: 5
        }
    ],

    listeners: {
        beforerender: 'onMainViewBeforeRender',
        scope: 'controller'
    }

});