/*
 * File: app/view/Restructure/ARCard.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Restructure.ARCard', {
    extend: 'Ext.window.Window',
    alias: 'widget.restructurearcard',

    requires: [
        'TabUserInformation.view.Restructure.ARCardViewModel',
        'TabUserInformation.view.Restructure.ARCardViewController',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Display',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'restructurearcard',
    viewModel: {
        type: 'restructurearcard'
    },
    title: 'Restructure - Create New Simulation',
    width: 600,
    //modal: true,
    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            bodyPadding: 10,
            items: [
                {
                    xtype: 'form',
                    id: 'head-restructure-form2',
                    defaults: {
                        labelWidth: 200,
                        labelAlign: 'right'
                    },
                    items: [
                        {
                            xtype: 'hiddenfield',
                            name: 'flag',
                            value: 'new'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'ID',
                            name: 'id',
                            value: '0'
                        },
                        {
                            xtype: 'hiddenfield',
                            name: 'SEQ',
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Agreement',
                            name: 'Agreement'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Customer',
                            name: 'Customer'
                        },
                        {
                            xtype: 'displayfield',
                            renderer: function(value, displayField) {
                                return Ext.Date.format(value, 'd/m/Y');
                            },
                            fieldLabel: 'Restructure Date',
                            name: 'RestructureDate',
                            reference: 'RestructureDate'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    id: 'arcard-form1',
                    itemId:'arcard-form1',
                    defaults: {
                        labelWidth: 200,
                        labelAlign: 'right',
                        //style: 'font-weight: bold',
                        //fieldCls: ''
                    },
                    items: [
                        {
                            xtype: 'container',
                            margin: '0 5 5 120',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'เงินต้นคงเหลือ',
                                    labelWidth: 'right',
                                    //width: 200,
                                    name: 'OS_PR',
                                    renderer: function(value, displayField) {
                                        return Ext.util.Format.number(value, '0,000.00');
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    reference: 'NewCheck',
                                    margin: '0 5 5 20',
                                    name: 'NewCheck',
                                    boxLabel: 'New'
                                },
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    fieldLabel: ' ',
                                    labelWidth: 5,
                                    name: 'New_OS_PR',
                                    bind: {
                                        disabled: '{!NewCheck.checked}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'อัตราดอกเบี้ย',
                            name: 'FlatRate',
                            renderer: function(value, displayField) {
                                return Ext.util.Format.number(value, '0,000.00');
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'จำนวนวัน',
                            name: 'Day',
                            renderer: function(value, displayField) {
                                return Ext.util.Format.number(value, '0,000.00');
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'ดอกเบี้ย',
                            name: 'Interest',
                            renderer: function(value, displayField) {
                                return Ext.util.Format.number(value, '0,000.00');
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Unpaid VAT for Restructure',
                            name: 'UnpaidVAT',
                            renderer: function(value, displayField) {
                                return Ext.util.Format.number(value, '0,000.00');
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'ค้างชำระเบี้ยปรับ+ค่าใช้จ่าย',
                            name: 'Penalty',
                            renderer: function(value, displayField) {
                                return Ext.util.Format.number(value, '0,000.00');
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Debit Note ค้างชำระ',
                            name: 'DebitNote',
                            renderer: function(value, displayField) {
                                return Ext.util.Format.number(value, '0,000.00');
                            }
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'New Flat Rate (Est.)',
                            name: 'NewFlatRate',
                            maxValue: 99.99,
                            minValue: 0.01,
                            step: 0.01,
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: 'New First Due Date',
                            name: 'NewFirstDueDate',
                            format: 'd/m/Y',
                            bind: {
                                minValue: '{today}'
                            },
                            allowBlank: false
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Subsequent Due Day',
                            name: 'SubsequentDueDay',
                            maxValue: 31,
                            minValue: -31,
                            allowBlank: false
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'New Term',
                            name: 'NewTerm',
                            minValue: 1,
                            allowBlank: false
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'saveButton',
                            ui: 'default-small',
                            text: 'Calculate Installment',
                            listeners: {
                                click: 'onCalculateInstallment'
                            }
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'cancelButton',
                            margin: 5,
                            ui: 'default-small',
                            text: 'Cancel',
                            listeners: {
                                click: 'onCancel'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onAfterRender'
    }

});