/*
 * File: app/view/Restructure/RestructureTabViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Restructure.RestructureTabViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.restructurerestructuretab',

    C1: function (NewFlatRate, NewTerm, OS_PR) {
        var result = ((OS_PR * (NewFlatRate / 100) * (NewTerm / 12)) + OS_PR) / NewTerm;

        return Ext.util.Format.round(result, 2);
    },

    onComboboxSelect: function (combo, records, eOpts) {
        var form = Ext.getCmp('head-restructure-form').getForm(),
            arcardForm = Ext.getCmp('arcard-form').getForm();

        arcardForm.reset();
        form.findField('Customer').setValue(records[0].get('Customer'));
    },

    onButtonARCardClick: function (button, e, eOpts) {
        var record = this.getStore('restructures').data.items[0],
            form = Ext.getCmp('arcard-form').getForm();

        form.loadRecord(record);

        // form.findField('NewFlatRate').setValue('');
        form.findField('NewFirstDueDate').setValue(Ext.Date.add(new Date(), Ext.Date.MONTH, 1));
        // form.findField('SubsequentDueDay').setValue('');
        // form.findField('NewTerm').setValue('');
    },

    onCalculateInstallment: function (button, e, eOpts) {
        //var form = Ext.getCmp('arcard-form').getForm(),
        var form = this.getView().down('form').getForm();

        if (form.isValid()) {
            var headform = Ext.getCmp('head-restructure-form').getForm(),
                values = form.getValues(),
                record = Ext.create('model.restructure', values);

            form.updateRecord(record);

            var Installment = TabUserInformation.view.Restructure.RestructureWindowViewController.C1(record);

            //C5 Calculate EffectiveRate
            Ext.Ajax.request({
                method: 'get',
                url: 'api/installment/geteffectiverate',
                params: {
                    Installment: Installment,
                    NewTerm: record.get('NewTerm'),
                    OS_PR: record.get('OS_PR') * -1
                },
                success: function (response) {
                    record.set('EffectiveRate', response.responseText);

                    var popup = Ext.create('widget.restructurerestructurewindow', {
                        listeners: {
                            beforerender: function (panel, eOpts) {
                                panel.down('form').getForm().loadRecord(record);
                                panel.getViewModel().getStore('restructures').loadRecords(record, {
                                    addRecords: true
                                });
                            }
                        }
                    });

                    popup.show();
                },
                failure: function (response) {
                }
            });

        } else {

        }
    },

    onCancel: function (button, e, eOpts) {
        var form = this.getView().down('form').getForm();
        form.reset();
    }

});
