/*
 * File: app/view/Window/ApplicationWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Window.ApplicationWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowapplicationwindow',

    requires: [
        'TabUserInformation.view.Window.ApplicationWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Hidden',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar'
    ],

    viewModel: {
        type: 'windowapplicationwindow'
    },
    title: 'Application',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            layout: {
                type: 'table',
                columns: 4
            },
            items: [
                {
                    xtype: 'container',
                    colspan: 4,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '0 0 5 0',
                            width: 250,
                            fieldLabel: 'Application #',
                            labelWidth: 140
                        },
                        {
                            xtype: 'container',
                            width: 420,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'combobox',
                                    width: 100
                                },
                                {
                                    xtype: 'datefield',
                                    margin: '0 0 0 5',
                                    width: 150,
                                    fieldLabel: 'Date',
                                    labelWidth: 30
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 0 5',
                                    width: 160,
                                    fieldLabel: 'Primary Job#',
                                    labelWidth: 80
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Industry Code #',
                                    labelWidth: 140
                                },
                                {
                                    xtype: 'textfield'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    colspan: 1,
                    width: 250,
                    fieldLabel: 'Agreement No',
                    labelWidth: 140
                },
                {
                    xtype: 'textfield',
                    colspan: 1,
                    margin: '0 0 0 5',
                    width: 200,
                    fieldLabel: 'Schedule No'
                },
                {
                    xtype: 'hiddenfield',
                    hidden: false,
                    width: 150,
                    fieldLabel: 'Space'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Nature of Cus',
                    labelWidth: 140
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    fieldLabel: 'Customer Code',
                    labelWidth: 140
                },
                {
                    xtype: 'textfield',
                    colspan: 2,
                    margin: '0 0 0 5',
                    width: 200,
                    fieldLabel: 'Indication Line'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Group of Cus',
                    labelWidth: 140
                },
                {
                    xtype: 'textfield',
                    colspan: 3,
                    width: 670,
                    fieldLabel: 'Customer Name',
                    labelWidth: 140
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Type of Lease',
                    labelWidth: 140
                },
                {
                    xtype: 'container',
                    colspan: 3,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'button',
                            width: 140,
                            text: 'Assign To Customer'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 0 5',
                            width: 105
                        },
                        {
                            xtype: 'textfield',
                            width: 420
                        }
                    ]
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Type of Equipment',
                    labelWidth: 140
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    fieldLabel: 'Telephone',
                    labelWidth: 140,
                    inputType: 'tel'
                },
                {
                    xtype: 'textfield',
                    colspan: 2,
                    margin: '0 0 0 5',
                    fieldLabel: 'Fax',
                    labelWidth: 50,
                    inputType: 'tel'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Type of Business',
                    labelWidth: 140
                },
                {
                    xtype: 'textfield',
                    colspan: 3,
                    width: 250,
                    fieldLabel: 'Business',
                    labelWidth: 140
                },
                {
                    xtype: 'textfield',
                    colspan: 1,
                    fieldLabel: 'Type of Customer',
                    labelWidth: 140
                },
                {
                    xtype: 'container',
                    colspan: 4,
                    margin: '0 0 5 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            width: '40%',
                            fieldLabel: 'Source of Information',
                            labelWidth: 140
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 0 5',
                            width: '60%',
                            fieldLabel: 'Detail when others',
                            labelWidth: 140
                        }
                    ]
                },
                {
                    xtype: 'datefield',
                    colspan: 1,
                    width: 250,
                    fieldLabel: 'Agreement Date',
                    labelWidth: 140
                },
                {
                    xtype: 'datefield',
                    colspan: 1,
                    margin: '0 0 0 5',
                    width: 250,
                    fieldLabel: 'Original Execute Date',
                    labelWidth: 140
                },
                {
                    xtype: 'container',
                    colspan: 2,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'combobox',
                            width: 150,
                            fieldLabel: 'Currency',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            width: 150,
                            fieldLabel: 'Exchange Rate'
                        },
                        {
                            xtype: 'textfield',
                            width: 100,
                            fieldLabel: 'Vat%',
                            labelWidth: 40
                        }
                    ]
                },
                {
                    xtype: 'datefield',
                    width: 250,
                    fieldLabel: 'Approve Date',
                    labelWidth: 140
                },
                {
                    xtype: 'datefield',
                    margin: '0 0 0 5',
                    width: 250,
                    fieldLabel: 'Last Execute Date',
                    labelWidth: 140
                },
                {
                    xtype: 'datefield',
                    colspan: 2,
                    width: 250,
                    fieldLabel: 'Current Execute Date',
                    labelWidth: 140
                },
                {
                    xtype: 'datefield',
                    width: 250,
                    fieldLabel: 'Amend Date',
                    labelWidth: 140
                },
                {
                    xtype: 'datefield',
                    margin: '0 0 0 5',
                    width: 250,
                    fieldLabel: 'Assign Date',
                    labelWidth: 140
                }
            ]
        },
        {
            xtype: 'gridpanel',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Boolean'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Boolean'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Deposit/Down Payment',
                            labelWidth: 150
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Equipment Cost BHT.',
                            labelWidth: 150
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'button',
                    text: 'History'
                },
                {
                    xtype: 'button',
                    text: 'Transaction'
                },
                {
                    xtype: 'button',
                    text: 'Revised Agreement'
                }
            ]
        }
    ]

});