/*
 * File: app/view/Window/VistiCallingWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Window.VistiCallingWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowvisticallingwindow',

    requires: [
        'TabUserInformation.view.Window.VistiCallingWindowViewModel',
        'TabUserInformation.view.Window.VistiCallingWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.field.TextArea',
        'Ext.form.field.Number',
        'Ext.form.FieldSet',
        'Ext.form.CheckboxGroup',
        'Ext.toolbar.Toolbar'
    ],

    controller: 'windowvisticallingwindow',
    viewModel: {
        type: 'windowvisticallingwindow'
    },
    autoShow: true,
    bodyPadding: 10,
    title: 'Visit/Calling Information',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            layout: 'auto',
            items: [
                {
                    xtype: 'container',
                    margin: '0 0 5 0',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 200,
                            fieldLabel: 'Visit #'
                        },
                        {
                            xtype: 'container',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'datefield',
                                    margin: '0 0 0 5',
                                    width: 150,
                                    fieldLabel: 'Date',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 0 5',
                                    width: 400,
                                    fieldLabel: 'Marketing Officer',
                                    labelWidth: 120
                                },
                                {
                                    xtype: 'checkboxfield',
                                    margin: '0 0 0 5',
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    boxLabel: 'Display'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'combobox',
                    margin: '',
                    width: 200,
                    fieldLabel: 'Method',
                    store: [
                        'Visiting',
                        'Calling'
                    ]
                },
                {
                    xtype: 'container',
                    margin: '5 0 5 0',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 200,
                            fieldLabel: 'Customer Code'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 5',
                            ui: 'default-small',
                            iconCls: 'x-form-search-trigger',
                            listeners: {
                                click: {
                                    fn: 'onButtonCusInfClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 5',
                            iconCls: 'x-form-search-trigger',
                            listeners: {
                                click: {
                                    fn: 'onButtonUserInfClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'combobox',
                            flex: 1,
                            margin: '0 0 0 5',
                            maxWidth: 250,
                            fieldLabel: 'Type of Customer',
                            labelWidth: 120
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '0 0 5 0',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'combobox',
                            width: 200,
                            fieldLabel: 'Name'
                        },
                        {
                            xtype: 'textfield',
                            width: 350
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'table',
                        columns: 5
                    },
                    items: [
                        {
                            xtype: 'textareafield',
                            colspan: 3,
                            rowspan: 4,
                            height: 120,
                            width: 550,
                            fieldLabel: 'Address'
                        },
                        {
                            xtype: 'button',
                            colspan: 2,
                            margin: '0 0 0 5',
                            iconCls: 'x-form-search-trigger',
                            listeners: {
                                click: {
                                    fn: 'onButtonAddressClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            margin: '0 0 0 5',
                            width: 280,
                            fieldLabel: 'Telephone',
                            labelWidth: 80,
                            inputType: 'tel'
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            margin: '0 0 0 5',
                            width: 280,
                            fieldLabel: 'Fax',
                            labelWidth: 80,
                            inputType: 'tel'
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            margin: '0 0 0 5',
                            width: 280,
                            fieldLabel: 'Email',
                            labelWidth: 80,
                            inputType: 'email'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'combobox',
                            width: 200,
                            fieldLabel: 'Province'
                        },
                        {
                            xtype: 'numberfield',
                            margin: '0 0 0 5',
                            width: 100,
                            fieldLabel: 'Zip',
                            labelWidth: 30,
                            hideTrigger: true
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '5 0 5 0',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            maxWidth: 200,
                            width: '',
                            fieldLabel: 'Contact Person'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            maxWidth: 315
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: '0 0 0 05',
                            maxWidth: 28,
                            iconCls: 'x-form-search-trigger',
                            listeners: {
                                click: {
                                    fn: 'onButtonContactPersonClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 5',
                            maxWidth: 280,
                            width: '',
                            fieldLabel: 'Position',
                            labelWidth: 80
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    width: 833,
                    fieldLabel: 'Business'
                },
                {
                    xtype: 'datefield',
                    width: 200,
                    fieldLabel: 'Establishment'
                },
                {
                    xtype: 'container',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'combobox',
                            width: 400,
                            fieldLabel: 'Source of Information',
                            labelWidth: 130
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 0 5',
                            width: 428,
                            fieldLabel: 'Detail when others',
                            labelWidth: 120
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'fieldset',
            id: 'financialpolicy',
            collapsible: true,
            title: 'Financial Policy',
            items: [
                {
                    xtype: 'checkboxgroup',
                    frame: false,
                    layout: {
                        type: 'checkboxgroup',
                        autoFlex: false
                    },
                    items: [
                        {
                            xtype: 'checkboxfield',
                            id: 'chk1',
                            margin: '0 0 0 5',
                            boxLabel: 'Cash',
                            listeners: {
                                change: 'onCheckboxfieldChange'
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            id: 'chk2',
                            margin: '0 0 0 5',
                            boxLabel: 'Loan',
                            listeners: {
                                change: 'onCheckboxfieldChange1'
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            margin: '0 0 0 5',
                            boxLabel: 'Lease',
                            listeners: {
                                change: 'onCheckboxfieldChange2'
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            margin: '0 0 0 5',
                            boxLabel: 'Hire Purschase',
                            listeners: {
                                change: 'onCheckboxfieldChange5'
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            margin: '0 0 0 5',
                            boxLabel: 'Loan Affiliated',
                            listeners: {
                                change: 'onCheckboxfieldChange3'
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            margin: '0 0 0 5',
                            boxLabel: 'Other',
                            listeners: {
                                change: 'onCheckboxfieldChange4'
                            }
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    cls: 'tpl-rw013k88',
                    id: 'financialpolicydetail',
                    fieldLabel: 'Detail when Lease or Hire Purchase',
                    labelAlign: 'top',
                    labelWidth: 250,
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'type-of-lease-equipment',
                            width: 800,
                            fieldLabel: 'Type of Lease Equipment',
                            labelWidth: 160
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'leasing-company',
                            width: 800,
                            fieldLabel: 'Leasing Company',
                            labelWidth: 160
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'term-and-condition',
                            width: 800,
                            fieldLabel: 'Term and Condition',
                            labelWidth: 160
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'type-of-hp-equipment',
                            width: 800,
                            fieldLabel: 'Type of HP Equipment',
                            labelWidth: 160
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'hp-company',
                            width: 800,
                            fieldLabel: 'HP Company',
                            labelWidth: 160
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'hp-term-and-condition',
                            width: 800,
                            fieldLabel: 'HP Term and Condition',
                            labelWidth: 160
                        },
                        {
                            xtype: 'textareafield',
                            hidden: true,
                            id: 'detail',
                            width: 800,
                            fieldLabel: 'Detail',
                            labelWidth: 160
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 120,
            collapsible: true,
            title: 'Project Plan',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Type of Equipment',
                    labelWidth: 120
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    maxWidth: 270,
                    fieldLabel: 'Amount',
                    labelWidth: 120,
                    hideTrigger: true
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    maxWidth: 220,
                    fieldLabel: 'Schedule',
                    labelWidth: 120,
                    inputType: 'month'
                }
            ]
        },
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'combobox',
                    fieldLabel: 'Result'
                },
                {
                    xtype: 'textfield',
                    width: 850,
                    fieldLabel: 'Other Comment'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    text: 'Reset'
                }
            ]
        }
    ],

    onCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        var textBox = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('detail');
        this.Shows(textBox,newValue);
    },

    onCheckboxfieldChange1: function(field, newValue, oldValue, eOpts) {
        var textBox = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('detail');
        this.Shows(textBox,newValue);
    },

    onCheckboxfieldChange2: function(field, newValue, oldValue, eOpts) {
        var textBox = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('type-of-lease-equipment');
        var textBox2 = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('leasing-company');
        var textBox3 = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('term-and-condition');
        this.ShowsDefault(textBox,newValue);
        this.ShowsDefault(textBox2,newValue);
        this.ShowsDefault(textBox3,newValue);
    },

    onCheckboxfieldChange5: function(field, newValue, oldValue, eOpts) {
        var textBox = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('type-of-hp-equipment');
        var textBox2 = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('hp-company');
        var textBox3 = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('hp-term-and-condition');
        this.ShowsDefault(textBox,newValue);
        this.ShowsDefault(textBox2,newValue);
        this.ShowsDefault(textBox3,newValue);
    },

    onCheckboxfieldChange3: function(field, newValue, oldValue, eOpts) {
        var textBox = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('detail');
        this.Shows(textBox,newValue);
    },

    onCheckboxfieldChange4: function(field, newValue, oldValue, eOpts) {
        var textBox = this.getComponent('financialpolicy').getComponent('financialpolicydetail').getComponent('detail');
        this.Shows(textBox,newValue);
    },

    Shows: function(field, status) {
        var chkboxgroup = this.getComponent('financialpolicy').items.items[0];

        if(status){
            field.show();
        }else{
            if(chkboxgroup.items.items[0].checked === true || chkboxgroup.items.items[1].checked === true ||
               chkboxgroup.items.items[4].checked === true || chkboxgroup.items.items[5].checked === true)
            { }
            else{
                field.hide();
            }
        }
    },

    ShowsDefault: function(field, status) {
        if(status){
        	field.show();
        }else{
        	field.hide();
         }
    }

});