/*
 * File: app/view/Role/RoleTabViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Role.RoleTabViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.roleroletab',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        roles: {
            pageSize: 10,
            autoLoad: false,
            model: 'TabUserInformation.model.Roles',
            proxy: {
                type: 'rest',
                url: '/api/role',
                api: {
                    create: '/api/role/Post',
                    read: '/api/role',
                    update: '/api/role',
                    destroy: '/api/role'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'items',
                    totalProperty: 'totalProperty'
                },
                wirter: {
                    type: 'json',
                    writeAllFields : true
                }
            }
        }
    }

});