/*
 * File: app/view/Job/Indication/IndicationForEquipmentTabViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Job.Indication.IndicationForEquipmentTabViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.jobindicationindicationforequipmenttab',

    onGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var grid = this.getView().down('grid');

        var popup = Ext.create('widget.jobindicationindicationforequipmentwindow', {
            listeners: {
                beforerender: function (panel, eOpts) {
                    var form = panel.down('form').getForm(),
                        grid = panel.down('grid'),
                        storeEquipment = grid.getStore();

                    form.loadRecord(record);

                    storeEquipment.getProxy().extraParams.indicationId = record.get('Id');
                    storeEquipment.load();
                    grid.view.refresh();
                },
                close: function (panel, eOpts) {
                    grid.view.refresh();
                }
            }
        });

        popup.show();
    },

    onButtonNewClick: function(button, e, eOpts) {
        var popup = Ext.create('widget.jobindicationindicationforequipmentwindow');
        popup.show();
    }

});
