/*
 * File: app/view/Job/Indication/IndicationDetailViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Job.Indication.IndicationDetailViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.jobindicationindicationdetail',

    onButtonSaveClick: function(button, e, eOpts) {
        var form = this.getView().down('form').getForm(),
            //panel = Ext.getCmp('jobjobwindow'),
            grid = Ext.getCmp('jobindicationindicationforequipmentwindow').down('grid'),
            store = grid.getStore(),
            record = grid.getSelection()[0];
            
            form.updateRecord(record);

        if (form.isValid()) {
//            form.submit({
//                url: 'api/equipment/post',
//                success: function (form, action) {
//                    Ext.Msg.alert('Success', 'บันทึกข้อมูลเรียบร้อยแล้ว');
//                },
//                failure: function (form, action) {
//                    Ext.Msg.alert('Failure', 'ไม่สำเร็จ');
//                }
//            });
            if (store.getModifiedRecords().length > 0) {
                store.sync({
                    success: function (batch, action) {
                        Ext.Msg.alert('Success', 'สำเร็จแล้ว');
                    },
                    failure: function (batch, action) {
                        Ext.Msg.alert('Failure', 'ไม่สำเร็จ');
                    }
                });
            }
        } else {
            Ext.Msg.alert('Failure', 'ข้อมูลไม่ถูกต้อง');
        }
    },
    
    onButtonNewClick: function(button, e, eOpts) {
        var popup = Ext.create('widget.jobapplicationapplicationdetail');
        popup.show();
    },

});
