/*
 * File: app/store/customerInformations.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.store.customerInformations', {
    extend: 'Ext.data.Store',
    alias: 'store.customerinformations',

    requires: [
        'TabUserInformation.model.CustomerInformation',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'customerInformations',
            model: 'TabUserInformation.model.CustomerInformation',
            data: [
                {
                    Code: 'fugiat',
                    'Name Eng': 'provident',
                    'Name Thai': 'maiores'
                },
                {
                    Code: 'rem',
                    'Name Eng': 'ad',
                    'Name Thai': 'est'
                },
                {
                    Code: 'velit',
                    'Name Eng': 'aliquid',
                    'Name Thai': 'laborum'
                },
                {
                    Code: 'ullam',
                    'Name Eng': 'quam',
                    'Name Thai': 'at'
                },
                {
                    Code: 'suscipit',
                    'Name Eng': 'dolor',
                    'Name Thai': 'qui'
                },
                {
                    Code: 'in',
                    'Name Eng': 'ratione',
                    'Name Thai': 'voluptate'
                },
                {
                    Code: 'aut',
                    'Name Eng': 'sequi',
                    'Name Thai': 'quod'
                },
                {
                    Code: 'ab',
                    'Name Eng': 'est',
                    'Name Thai': 'omnis'
                },
                {
                    Code: 'eum',
                    'Name Eng': 'et',
                    'Name Thai': 'laboriosam'
                },
                {
                    Code: 'voluptas',
                    'Name Eng': 'eveniet',
                    'Name Thai': 'aperiam'
                },
                {
                    Code: 'molestiae',
                    'Name Eng': 'ad',
                    'Name Thai': 'optio'
                },
                {
                    Code: 'ullam',
                    'Name Eng': 'harum',
                    'Name Thai': 'qui'
                },
                {
                    Code: 'aliquam',
                    'Name Eng': 'quis',
                    'Name Thai': 'similique'
                },
                {
                    Code: 'saepe',
                    'Name Eng': 'et',
                    'Name Thai': 'id'
                },
                {
                    Code: 'est',
                    'Name Eng': 'architecto',
                    'Name Thai': 'enim'
                },
                {
                    Code: 'aliquam',
                    'Name Eng': 'est',
                    'Name Thai': 'non'
                },
                {
                    Code: 'sint',
                    'Name Eng': 'impedit',
                    'Name Thai': 'nihil'
                },
                {
                    Code: 'aliquam',
                    'Name Eng': 'qui',
                    'Name Thai': 'quod'
                },
                {
                    Code: 'provident',
                    'Name Eng': 'aut',
                    'Name Thai': 'explicabo'
                },
                {
                    Code: 'aut',
                    'Name Eng': 'voluptatem',
                    'Name Thai': 'omnis'
                },
                {
                    Code: 'aperiam',
                    'Name Eng': 'ullam',
                    'Name Thai': 'accusamus'
                },
                {
                    Code: 'est',
                    'Name Eng': 'nesciunt',
                    'Name Thai': 'tempore'
                },
                {
                    Code: 'sapiente',
                    'Name Eng': 'est',
                    'Name Thai': 'consequatur'
                },
                {
                    Code: 'dolore',
                    'Name Eng': 'facere',
                    'Name Thai': 'atque'
                },
                {
                    Code: 'accusantium',
                    'Name Eng': 'omnis',
                    'Name Thai': 'rerum'
                },
                {
                    Code: 'id',
                    'Name Eng': 'aliquid',
                    'Name Thai': 'voluptas'
                },
                {
                    Code: 'eius',
                    'Name Eng': 'aut',
                    'Name Thai': 'consequatur'
                },
                {
                    Code: 'et',
                    'Name Eng': 'doloribus',
                    'Name Thai': 'nesciunt'
                },
                {
                    Code: 'quia',
                    'Name Eng': 'sequi',
                    'Name Thai': 'corrupti'
                },
                {
                    Code: 'ea',
                    'Name Eng': 'voluptas',
                    'Name Thai': 'est'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});