/*
 * File: app/store/bGs.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.store.bGs', {
    extend: 'Ext.data.Store',
    alias: 'store.bgs',

    requires: [
        'TabUserInformation.model.BG',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'bGs',
            model: 'TabUserInformation.model.BG',
            data: [
                {
                    Id: 60,
                    BGNo: 'rerum',
                    ReceiveDate: 'reprehenderit',
                    BGDate: 'iste',
                    Bank: 'sapiente',
                    Branch: 'voluptates',
                    Amount: 805.53,
                    ContactNo: 'consequatur'
                },
                {
                    Id: 761,
                    BGNo: 'error',
                    ReceiveDate: 'ab',
                    BGDate: 'beatae',
                    Bank: 'quos',
                    Branch: 'vitae',
                    Amount: 705.74,
                    ContactNo: 'perspiciatis'
                },
                {
                    Id: 295,
                    BGNo: 'perspiciatis',
                    ReceiveDate: 'fuga',
                    BGDate: 'aliquam',
                    Bank: 'voluptatem',
                    Branch: 'aut',
                    Amount: 852.7,
                    ContactNo: 'voluptates'
                },
                {
                    Id: 291,
                    BGNo: 'assumenda',
                    ReceiveDate: 'dicta',
                    BGDate: 'minima',
                    Bank: 'aperiam',
                    Branch: 'illo',
                    Amount: 824.87,
                    ContactNo: 'tenetur'
                },
                {
                    Id: 853,
                    BGNo: 'sint',
                    ReceiveDate: 'ullam',
                    BGDate: 'explicabo',
                    Bank: 'repellat',
                    Branch: 'iste',
                    Amount: 258.89,
                    ContactNo: 'dolor'
                },
                {
                    Id: 425,
                    BGNo: 'quo',
                    ReceiveDate: 'ut',
                    BGDate: 'sit',
                    Bank: 'facere',
                    Branch: 'corrupti',
                    Amount: 592.54,
                    ContactNo: 'rerum'
                },
                {
                    Id: 166,
                    BGNo: 'id',
                    ReceiveDate: 'ullam',
                    BGDate: 'qui',
                    Bank: 'sequi',
                    Branch: 'tempora',
                    Amount: 690.14,
                    ContactNo: 'natus'
                },
                {
                    Id: 461,
                    BGNo: 'rerum',
                    ReceiveDate: 'consequatur',
                    BGDate: 'velit',
                    Bank: 'quam',
                    Branch: 'sit',
                    Amount: 414.89,
                    ContactNo: 'provident'
                },
                {
                    Id: 253,
                    BGNo: 'voluptatem',
                    ReceiveDate: 'delectus',
                    BGDate: 'nihil',
                    Bank: 'error',
                    Branch: 'aliquam',
                    Amount: 801.65,
                    ContactNo: 'dolore'
                },
                {
                    Id: 613,
                    BGNo: 'adipisci',
                    ReceiveDate: 'optio',
                    BGDate: 'qui',
                    Bank: 'modi',
                    Branch: 'aut',
                    Amount: 905.4,
                    ContactNo: 'dolore'
                },
                {
                    Id: 684,
                    BGNo: 'ipsa',
                    ReceiveDate: 'vel',
                    BGDate: 'repudiandae',
                    Bank: 'dolor',
                    Branch: 'autem',
                    Amount: 750.15,
                    ContactNo: 'molestias'
                },
                {
                    Id: 849,
                    BGNo: 'animi',
                    ReceiveDate: 'dolorum',
                    BGDate: 'quis',
                    Bank: 'velit',
                    Branch: 'est',
                    Amount: 280.29,
                    ContactNo: 'repudiandae'
                },
                {
                    Id: 460,
                    BGNo: 'magnam',
                    ReceiveDate: 'aut',
                    BGDate: 'tempora',
                    Bank: 'odio',
                    Branch: 'modi',
                    Amount: 592.78,
                    ContactNo: 'dolorem'
                },
                {
                    Id: 761,
                    BGNo: 'excepturi',
                    ReceiveDate: 'aspernatur',
                    BGDate: 'id',
                    Bank: 'et',
                    Branch: 'distinctio',
                    Amount: 181.75,
                    ContactNo: 'consequatur'
                },
                {
                    Id: 676,
                    BGNo: 'voluptas',
                    ReceiveDate: 'mollitia',
                    BGDate: 'assumenda',
                    Bank: 'libero',
                    Branch: 'omnis',
                    Amount: 410,
                    ContactNo: 'dolorem'
                },
                {
                    Id: 12,
                    BGNo: 'ullam',
                    ReceiveDate: 'quia',
                    BGDate: 'veniam',
                    Bank: 'facere',
                    Branch: 'aut',
                    Amount: 196.54,
                    ContactNo: 'dolor'
                },
                {
                    Id: 957,
                    BGNo: 'qui',
                    ReceiveDate: 'rem',
                    BGDate: 'illo',
                    Bank: 'aliquam',
                    Branch: 'ipsa',
                    Amount: 517.26,
                    ContactNo: 'excepturi'
                },
                {
                    Id: 596,
                    BGNo: 'ad',
                    ReceiveDate: 'facere',
                    BGDate: 'voluptas',
                    Bank: 'praesentium',
                    Branch: 'nihil',
                    Amount: 685.39,
                    ContactNo: 'officia'
                },
                {
                    Id: 811,
                    BGNo: 'rerum',
                    ReceiveDate: 'et',
                    BGDate: 'tenetur',
                    Bank: 'ex',
                    Branch: 'minus',
                    Amount: 309.65,
                    ContactNo: 'occaecati'
                },
                {
                    Id: 473,
                    BGNo: 'quia',
                    ReceiveDate: 'qui',
                    BGDate: 'et',
                    Bank: 'ea',
                    Branch: 'dolorem',
                    Amount: 227,
                    ContactNo: 'et'
                },
                {
                    Id: 91,
                    BGNo: 'quo',
                    ReceiveDate: 'error',
                    BGDate: 'reprehenderit',
                    Bank: 'dolorem',
                    Branch: 'aut',
                    Amount: 159.63,
                    ContactNo: 'suscipit'
                },
                {
                    Id: 67,
                    BGNo: 'eaque',
                    ReceiveDate: 'repellendus',
                    BGDate: 'ratione',
                    Bank: 'quo',
                    Branch: 'dolorem',
                    Amount: 364.08,
                    ContactNo: 'distinctio'
                },
                {
                    Id: 59,
                    BGNo: 'at',
                    ReceiveDate: 'sit',
                    BGDate: 'odit',
                    Bank: 'eos',
                    Branch: 'excepturi',
                    Amount: 699.8,
                    ContactNo: 'sunt'
                },
                {
                    Id: 159,
                    BGNo: 'earum',
                    ReceiveDate: 'explicabo',
                    BGDate: 'recusandae',
                    Bank: 'eum',
                    Branch: 'voluptas',
                    Amount: 862.82,
                    ContactNo: 'ut'
                },
                {
                    Id: 46,
                    BGNo: 'velit',
                    ReceiveDate: 'ducimus',
                    BGDate: 'ducimus',
                    Bank: 'assumenda',
                    Branch: 'illum',
                    Amount: 147.87,
                    ContactNo: 'qui'
                },
                {
                    Id: 907,
                    BGNo: 'eveniet',
                    ReceiveDate: 'natus',
                    BGDate: 'ratione',
                    Bank: 'minus',
                    Branch: 'praesentium',
                    Amount: 715.24,
                    ContactNo: 'sapiente'
                },
                {
                    Id: 719,
                    BGNo: 'voluptatem',
                    ReceiveDate: 'dicta',
                    BGDate: 'illo',
                    Bank: 'sed',
                    Branch: 'error',
                    Amount: 446.99,
                    ContactNo: 'dolorem'
                },
                {
                    Id: 674,
                    BGNo: 'qui',
                    ReceiveDate: 'labore',
                    BGDate: 'similique',
                    Bank: 'soluta',
                    Branch: 'voluptate',
                    Amount: 281.64,
                    ContactNo: 'reiciendis'
                },
                {
                    Id: 386,
                    BGNo: 'magni',
                    ReceiveDate: 'rem',
                    BGDate: 'tenetur',
                    Bank: 'dolorem',
                    Branch: 'at',
                    Amount: 670.94,
                    ContactNo: 'minima'
                },
                {
                    Id: 572,
                    BGNo: 'eos',
                    ReceiveDate: 'id',
                    BGDate: 'dicta',
                    Bank: 'omnis',
                    Branch: 'ut',
                    Amount: 913.11,
                    ContactNo: 'dolorem'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});