/*
 * File: app/store/customerInformations.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.store.customers', {
    extend: 'Ext.data.Store',
    alias: 'store.customers',

    requires: [
        'TabUserInformation.model.Customer',
        'Ext.data.proxy.Rest'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'customers',
            model: 'TabUserInformation.model.Customer',
            //autoLoad: true,
            proxy: {
                type: 'rest',
                url: 'api/CusInfo',
                reader: {
                    type: 'json',
                    rootProperty: 'data',
                    totalProperty: 'total'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    dateFormat: 'c'
                },
                api: {
                    create: 'api/CusInfo/Post'
                }
            },
            sorters: [{
                property: 'FullNameTh',
                direction: 'ASC'
            }],
        }, cfg)]);
    }
});