/*
 * File: app/store/dueDays.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.store.dueDays', {
    extend: 'Ext.data.Store',
    alias: 'store.duedays',

    requires: [
        'TabUserInformation.model.DueDay',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'dueDays',
            model: 'TabUserInformation.model.DueDay',
            data: [
                {
                    Id: 983,
                    AppId: 616,
                    DueDay: 668
                },
                {
                    Id: 958,
                    AppId: 698,
                    DueDay: 809
                },
                {
                    Id: 4,
                    AppId: 187,
                    DueDay: 98
                },
                {
                    Id: 999,
                    AppId: 272,
                    DueDay: 96
                },
                {
                    Id: 417,
                    AppId: 180,
                    DueDay: 798
                },
                {
                    Id: 139,
                    AppId: 823,
                    DueDay: 243
                },
                {
                    Id: 339,
                    AppId: 343,
                    DueDay: 883
                },
                {
                    Id: 59,
                    AppId: 791,
                    DueDay: 672
                },
                {
                    Id: 665,
                    AppId: 169,
                    DueDay: 868
                },
                {
                    Id: 69,
                    AppId: 143,
                    DueDay: 963
                },
                {
                    Id: 678,
                    AppId: 285,
                    DueDay: 720
                },
                {
                    Id: 701,
                    AppId: 853,
                    DueDay: 82
                },
                {
                    Id: 755,
                    AppId: 641,
                    DueDay: 15
                },
                {
                    Id: 780,
                    AppId: 617,
                    DueDay: 848
                },
                {
                    Id: 117,
                    AppId: 687,
                    DueDay: 100
                },
                {
                    Id: 828,
                    AppId: 75,
                    DueDay: 793
                },
                {
                    Id: 715,
                    AppId: 538,
                    DueDay: 801
                },
                {
                    Id: 411,
                    AppId: 587,
                    DueDay: 344
                },
                {
                    Id: 915,
                    AppId: 56,
                    DueDay: 386
                },
                {
                    Id: 344,
                    AppId: 920,
                    DueDay: 12
                },
                {
                    Id: 541,
                    AppId: 281,
                    DueDay: 684
                },
                {
                    Id: 104,
                    AppId: 518,
                    DueDay: 103
                },
                {
                    Id: 911,
                    AppId: 773,
                    DueDay: 863
                },
                {
                    Id: 268,
                    AppId: 535,
                    DueDay: 574
                },
                {
                    Id: 949,
                    AppId: 80,
                    DueDay: 248
                },
                {
                    Id: 940,
                    AppId: 139,
                    DueDay: 396
                },
                {
                    Id: 46,
                    AppId: 129,
                    DueDay: 825
                },
                {
                    Id: 879,
                    AppId: 879,
                    DueDay: 988
                },
                {
                    Id: 48,
                    AppId: 681,
                    DueDay: 529
                },
                {
                    Id: 379,
                    AppId: 705,
                    DueDay: 37
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});