/*
 * File: app/store/guarantorModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.store.guarantorModels', {
    extend: 'Ext.data.Store',
    alias: 'store.guarantormodels',

    requires: [
        'TabUserInformation.model.GuarantorModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'guarantorModels',
            model: 'TabUserInformation.model.GuarantorModel',
            proxy: {
                type: 'rest',
                url: 'api/Guarantor',
                reader: {
                    type: 'json',
                    totalProperty: 'total',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    allowSingle: false
                },
                api: {
                    create: 'api/Guarantor/Post'
                }
            },
            sorters: [{
                property: 'Id',
                direction: 'ASC'
            }]
        }, cfg)]);
    }
});