/*
 * File: app/view/Approve/ApprovalWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Approve.ApprovalWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.approveapprovalwindow',

    requires: [
        'TabUserInformation.view.Approve.ApprovalWindowViewModel',
        'TabUserInformation.view.Approve.ApprovalWindowViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'approveapprovalwindow',
    viewModel: {
        type: 'approveapprovalwindow'
    },
    autoShow: true,
    width: 800,
    bodyBorder: true,
    bodyPadding: 10,
    title: 'Approval',
    modal: true,

    dockedItems: [
        {
            xtype: 'gridpanel',
            dock: 'left',
            width: 360,
            forceFit: true,
            store: 'approvals',
            columns: [
                {
                    xtype: 'rownumberer',
                    sortable: false
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ApprovedBy',
                    text: 'Approve By',
                    sortable: false
                }
            ],
            listeners: {
                selectionchange: 'onGridpanelSelectionChange',
                deselect: 'onGridpanelDeselect'
            }
        },
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    text: 'New',
                    listeners: {
                        click: 'onButtonNewClick'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Save',
                    listeners: {
                        click: 'onButtonSaveClick'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Delete',
                    listeners: {
                        click: 'onButtonDeleteClick'
                    }
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Request IRR',
                    labelAlign: 'right'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'hiddenfield',
            itemId: 'InformationId'
        },
        {
            xtype: 'form',
            itemId: 'approveForm',
            defaults: {
                allowBlank: false,
                
            },
            titleCollapse: false,
            items: [
                
                {
                    xtype: 'container',
                    width: 400,
                    defaults: {
                        allowBlank: false,
                        labelWidth: 150
                    },
                    layout: 'form',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Approved By',
                            labelAlign: 'right',
                            name: 'ApprovedBy'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Position',
                            labelAlign: 'right',
                            name: 'Position'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    width: 400,
                    defaults: {
                        allowBlank: false
                    },
                    title: 'Approve Result',
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'checkboxgroup',
                            rowspan: 2,
                            layout: 'auto',
                            labelWidth: 0,
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    labelWidth: 0,
                                    name: 'Approve',
                                    boxLabel: 'Approve'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    labelWidth: 0,
                                    name: 'Unquote',
                                    boxLabel: 'Unquote'
                                }
                            ],
                            allowBlank: true
                        },
                        {
                            xtype: 'datefield',
                            colspan: 2,
                            width: 220,
                            fieldLabel: 'Approval Date',
                            labelAlign: 'right',
                            name: 'ApprovalDate',
                            altFormats: 'd/m/Y|j/n/Y|j/n/y|m/j/y|n/d/y|m/j/Y|n/d/Y|d-m-y|d-m-Y|d/m|d-m|dm|dmy|dmY|d|Y-d-m|n-j|j/n',
                            format: 'd/m/Y',
                            allowBlank: true
                        },
                        {
                            xtype: 'datefield',
                            width: 220,
                            fieldLabel: 'Unquote Date',
                            labelAlign: 'right',
                            name: 'UnquoteDate',
                            altFormats: 'd/m/Y|j/n/Y|j/n/y|m/j/y|n/d/y|m/j/Y|n/d/Y|d-m-y|d-m-Y|d/m|d-m|dm|dmy|dmY|d|Y-d-m|n-j|j/n',
                            format: 'd/m/Y',
                            allowBlank: true
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    width: 400,
                    defaults: {
                        allowBlank: false,
                        labelWidth: 150
                    },
                    layout: 'form',
                    title: 'Condition',
                    items: [
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Min.IRR %',
                            labelAlign: 'right',
                            name: 'MinIRR'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'PDC',
                            labelAlign: 'right',
                            name: 'PDC'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'RV %',
                            labelAlign: 'right',
                            name: 'RV'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Deposit %',
                            labelAlign: 'right',
                            name: 'Deposit'
                        },
                        {
                            xtype: 'checkboxgroup',
                            labelWidth: 0,
                            layout: {
                                type: 'checkboxgroup',
                                autoFlex: false
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    labelWidth: 0,
                                    name: 'PG',
                                    boxLabel: 'PG'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    labelWidth: 0,
                                    name: 'CG',
                                    boxLabel: 'CG'
                                }
                            ],
                            allowBlank: true
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Condition of Lease',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'ConditionLease',
                            autoLoadOnValue: true,
                            displayField: 'Name',
                            store: 'CommonData.conditionLease',
                            valueField: 'Id'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Inurances paid by',
                            labelAlign: 'right',
                            labelWidth: 150,
                            name: 'InsPaid',
                            autoLoadOnValue: true,
                            displayField: 'Name',
                            store: 'CommonData.borneBy',
                            valueField: 'Id'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    width: 400,
                    defaults: {
                        labelWidth: 150
                    },
                    layout: 'form',
                    title: 'Other Condition',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Other',
                            labelAlign: 'right',
                            name: 'Other'
                        },
                        {
                            xtype: 'textareafield',
                            width: 400,
                            fieldLabel: 'Comment',
                            labelAlign: 'right',
                            name: 'Comment'
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforeclose: 'onWindowBeforeClose',
        close: 'onWindowClose'
    }

});