/*
 * File: app/view/Approve/ApprovalWindowViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Approve.ApprovalWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.approveapprovalwindow',

    onGridpanelSelectionChange: function(model, selected, eOpts) {
        var form = this.getView().down('form').getForm();

        if(selected[0] !== null){
            form.loadRecord(selected[0]);
        }
    },

    onGridpanelDeselect: function(rowmodel, record, index, eOpts) {
        var form = this.getView().down('form').getForm();

        form.updateRecord(record);
    },

    onButtonNewClick: function(button, e, eOpts) {
        var grid = this.getView().down('grid'),
            form = this.getView().down('form'),
            store = grid.getStore(),
            record = Ext.create('model.approval');

        store.add(record);
        grid.getView().setSelection(record);
        form.reset();
    },

    onButtonSaveClick: function(button, e, eOpts) {
        var view = this.getView(),
            form = view.down('form').getForm(),
            store = view.down('grid').getStore();

        Ext.Msg.show({
            title: 'Save Changes?',
            message: 'คุณต้องการบันทึกข้อมูลหรือไม่?',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.QUESTION,
            fn: function (btn) {
                if (btn === 'yes') {
                    if(form.isValid()){
                        store.sync({
                            success: function(batch){

                            },
                            failed:function(batch){

                            }
                        });
                    }else{
                        Ext.MessageBox.alert('Warning','กรอกข้อมูลไม่ครบถ้วน');
                    }
                } else {
                }
            }
        });
    },

    onButtonDeleteClick: function(button, e, eOpts) {
        var grid = this.getView().down('grid'),
            store = grid.getStore(),
            record = grid.getSelection()[0];

        if(record){
            Ext.Msg.show({
                title: 'Delete?',
                message: 'คุณต้องการลบข้อมูลหรือไม่?',
                buttons: Ext.Msg.YESNO,
                icon: Ext.Msg.QUESTION,
                fn: function (btn) {
                    if (btn === 'yes') {
                        store.remove(record);
                    }
                }
            });
        }
    },

    onWindowBeforeClose: function(panel, eOpts) {
        var view = this.getView(),
            form = view.down('form').getForm(),
            grid = view.down('grid'),
            store = grid.getStore(),
            selected = grid.getSelectionModel().getSelection();

        if (view.closeMe) {
            view.closeMe = false;
            return true;
        }

        if(selected[0]){
            form.updateRecord(selected[0]);
        }

        if(store.getModifiedRecords().length > 0){
            Ext.MessageBox.show({
                title: 'Save Changes?',
                message: 'คุณต้องการบันทึกข้อมูลหรือไม่?',
                buttons: Ext.Msg.YESNOCANCEL,
                icon: Ext.Msg.QUESTION,
                width: 300,
                fn: function (btn) {
                    if (btn === 'yes') {
                        store.sync({
                            success: function(batch){

                            },
                            failed:function(batch){

                            }
                        });
                        view.close();
                        view.closeMe = true;
                    } else if(btn === 'no'){
                        view.close();
                        view.closeMe = true;
                    }else {
                    }
                }
            });

            return false;
        }

    }

});
