/*
 * File: app/model/ApplicationDetailView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.model.ApplicationDetailView', {
    extend: 'Ext.data.Model',
    alias: 'model.applicationdetailview',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Number'
    ],

    idProperty: 'Id',

    fields: [
//        {
//            name: 'ApplicationDetail'
//        },
//        {
//            name: 'WaiveDocument'
//        },
//        {
//            name: 'Guarantor'
//        },
//        {
//            name: 'OptionEndLeaseTerm'
//        },
//        {
//            name: 'MethodPayment'
//        },
//        {
//            name: 'Maintenance'
//        },
//        {
//            name: 'Insurance'
//        },
//        {
//            name: 'Commission'
//        },
//        {
//            name: 'StampDuty'
//        },
//        {
//            name: 'StipulateLoss'
//        },
//        {
//            name: 'Funding'
//        },
//        {
//            name: 'TermCondition'
//        },
//        {
//            type: 'int',
//            name: 'Id'
//        },
//        {
//            type: 'string',
//            name: 'Code'
//        },
//        {
//            type: 'string',
//            name: 'Name'
//        },
//        {
//            type: 'int',
//            defaultValue: 2014,
//            name: 'Year'
//        },
//        {
//            type: 'string',
//            name: 'ApplicationId'
//        },
//        {
//            type: 'int',
//            name: 'ApplicationType'
//        },
//        {
//            type: 'string',
//            name: 'ApplicationDate'
//        },
//        {
//            type: 'int',
//            name: 'PrimaryJob'
//        },
//        {
//            type: 'string',
//            name: 'IndicationLine'
//        },
//        {
//            type: 'int',
//            name: 'Status'
//        },
//        {
//            type: 'string',
//            name: 'AgreementNo'
//        },
//        {
//            type: 'int',
//            name: 'IntegralPartNo'
//        },
//        {
//            type: 'string',
//            name: 'ScheduleNo'
//        },
//        {
//            type: 'string',
//            name: 'CustomerCode'
//        },
//        {
//            type: 'string',
//            name: 'CustomerName'
//        },
//        {
//            type: 'string',
//            name: 'Telephone'
//        },
//        {
//            type: 'string',
//            name: 'Fax'
//        },
//        {
//            type: 'string',
//            name: 'MarketingOfficer'
//        },
//        {
//            type: 'int',
//            name: 'IndustryCode'
//        },
//        {
//            type: 'int',
//            name: 'NatureCust'
//        },
//        {
//            type: 'int',
//            name: 'GroupCust'
//        },
//        {
//            type: 'int',
//            name: 'TypeLease'
//        },
//        {
//            type: 'int',
//            name: 'TypeEquipment'
//        },
//        {
//            type: 'int',
//            name: 'TypeBusiness'
//        },
//        {
//            type: 'int',
//            name: 'TypeCustomer'
//        },
//        {
//            type: 'string',
//            name: 'Business'
//        },
//        {
//            type: 'int',
//            name: 'SourceInformation'
//        },
//        {
//            name: 'Remark'
//        },
//        {
//            type: 'string',
//            name: 'ApproveDate'
//        },
//        {
//            type: 'string',
//            name: 'DeliveryDate'
//        },
//        {
//            type: 'string',
//            name: 'AgreementDate'
//        },
//        {
//            type: 'string',
//            name: 'ExecuteDate'
//        },
//        {
//            type: 'string',
//            name: 'ScheduleDate'
//        },
//        {
//            type: 'float',
//            name: 'VAT'
//        },
//        {
//            type: 'int',
//            name: 'Currency'
//        },
//        {
//            type: 'float',
//            name: 'ExchangeRate'
//        },
//        {
//            type: 'int',
//            name: 'Rating'
//        },
//        {
//            type: 'float',
//            name: 'ExposureLimit'
//        },
//        {
//            type: 'string',
//            name: 'RatingDetail'
//        },
//        {
//            type: 'string',
//            name: 'RatingDate'
//        },
//        {
//            type: 'string',
//            name: 'CreateDate'
//        },
//        {
//            name: 'CreateBy'
//        },
//        {
//            type: 'string',
//            name: 'UpdateDate'
//        },
//        {
//            name: 'UpdateBy'
    //        }
{
name: 'AgreementDate'
},
{
    name: 'AgreementNo'
},
{
    name: 'ApplicationDate'
},
{
    name: 'ApplicationDetail'
},
{
    name: 'ApplicationId'
},
{
    name: 'ApplicationType'
},
{
    name: 'ApproveDate'
},
{
    name: 'Business'
},
{
    name: 'Code'
},
{
    name: 'Commission'
},
{
    name: 'CreateBy'
},
{
    name: 'CreateDate'
},
{
    name: 'Currency'
},
{
    name: 'CustomerCode'
},
{
    name: 'CustomerName'
},
{
    name: 'DeliveryDate'
},
{
    name: 'ExchangeRate'
},
{
    name: 'ExecuteDate'
},
{
    name: 'ExposureLimit'
},
{
    name: 'Fax'
},
{
    name: 'Funding'
},
{
    name: 'GroupCust'
},
{
    name: 'Guarantor'
},
{
    name: 'Id'
},
{
    name: 'IndicationLine'
},
{
    name: 'IndustryCode'
},
{
    name: 'Insurance'
},
{
    name: 'IntegralPartNo'
},
{
    name: 'Maintenance'
},
{
    name: 'MarketingOfficer'
},
{
    name: 'MethodPayment'
},
{
    name: 'Name'
},
{
    name: 'NatureCust'
},
{
    name: 'OptionEndLeaseTerm'
},
{
    name: 'PrimaryJob'
},
{
    name: 'Rating'
},
{
    name: 'RatingDate'
},
{
    name: 'RatingDetail'
},
{
    name: 'Remark'
},
{
    name: 'ScheduleDate'
},
{
    name: 'ScheduleNo'
},
{
    name: 'SourceInformation'
},
{
    name: 'StampDuty'
},
{
    name: 'Status'
},
{
    name: 'StipulateLoss'
},
{
    name: 'Telephone'
},
{
    name: 'TermCondition'
},
{
    name: 'TypeBusiness'
},
{
    name: 'TypeCustomer'
},
{
    name: 'TypeEquipment'
},
{
    name: 'TypeLease'
},
{
    name: 'UpdateBy'
},
{
    name: 'UpdateDate'
},
{
    name: 'VAT'
},
{
    name: 'WaiveDocument'
},
{
    name: 'Year'
}
    ]
    });

