/*
* File: app/model/CommonAddress.js
*
* This file was generated by Sencha Architect version 3.1.0.
* http://www.sencha.com/products/architect/
*
* This file requires use of the Ext JS 5.0.x library, under independent license.
* License of Sencha Architect does not include license for Ext JS 5.0.x. For more
* details see http://www.sencha.com/license or contact license@sencha.com.
*
* This file will be auto-generated each and everytime you save your project.
*
* Do NOT hand edit this file.
*/

Ext.define('TabUserInformation.model.CommonAddress', {
    extend: 'Ext.data.Model',
    alias: 'model.commonaddress',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'int',
            name: 'Id',
            convert: undefined
        },
        {
            type: 'int',
            name: 'Parent_Id',
            convert: undefined
        },
        {
            type: 'int',
            name: 'Levels',
            convert: undefined
        },
        {
            type: 'string',
            name: 'Name',
            convert: undefined
        },

        {
            type: 'bool',
            name: 'IsLeaf',
            convert: undefined
        }
    ]
    
    ,idProperty: 'Id'
});