/*
 * File: app/model/Guarantor.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.model.Guarantor', {
    extend: 'Ext.data.Model',
    alias: 'model.guarantor',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    idProperty: 'Id',

    fields: [
        {
            type: 'int',
            name: 'Id'
        },
        {
            type: 'int',
            name: 'AppId'
        },
        {
            type: 'int',
            name: 'ConditionLease'
        },
        {
            name: 'BGNo'
        },
        {
            type: 'date',
            name: 'BGReceivedDate',
            dateWriteFormat: 'MS'
        },
        {
            type: 'date',
            name: 'ConfirmPrintedDate',
            dateWriteFormat: 'MS'
        },
        {
            type: 'date',
            name: 'ReturnDate',
            dateWriteFormat: 'MS'
        },
        {
            type: 'int',
            name: 'Bank'
        },
        {
            name: 'Branch'
        },
        {
            type: 'float',
            name: 'BGAmount'
        },
        {
            type: 'date',
            name: 'BGDate',
            dateWriteFormat: 'MS'
        },
        {
            type: 'date',
            name: 'PeriodFrom',
            dateWriteFormat: 'MS'
        },
        {
            type: 'date',
            name: 'PeriodTo',
            dateWriteFormat: 'MS'
        },
        {
            name: 'BuyerName'
        },
        {
            type: 'float',
            name: 'RSAAmount'
        },
        {
            type: 'date',
            name: 'EquipmentSalesPrintedDate',
            dateWriteFormat: 'MS'
        },
        {
            name: 'Signer1EquipmentSales'
        },
        {
            name: 'Signer2EquipmentSales'
        },
        {
            name: 'WithnessEquipmentSales'
        },
        {
            name: 'AddressEquipmentSales'
        },
        {
            type: 'int',
            name: 'Collateral'
        },
        {
            name: 'CollateralDetail'
        },
        {
            name: 'AdditionalCondition'
        }
    ]
});