/*
 * File: app/model/InsuranceEquipment.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.model.InsuranceEquipment', {
    extend: 'Ext.data.Model',
    alias: 'model.insuranceequipment',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    idProperty: 'Id',

    fields: [
        {
            type: 'int',
            name: 'Id'
        },
        {
            type: 'int',
            name: 'AppId'
        },
        {
            name: 'EquipmentType'
        },
        {
            type: 'int',
            name: 'Chassis'
        },
        {
            name: 'Licens'
        },
        {
            type: 'date',
            name: 'StartDate'
        },
        {
            type: 'date',
            name: 'EndDate'
        },
        {
            type: 'float',
            name: 'Rate'
        },
        {
            type: 'float',
            name: 'SumInsured'
        },
        {
            type: 'float',
            name: 'Premium'
        },
        {
            type: 'int',
            name: 'Territory'
        },
        {
            type: 'float',
            name: 'Deductible'
        },
        {
            name: 'PaymentInsRate'
        },
        {
            type: 'float',
            name: 'Minimum'
        },
        {
            type: 'float',
            name: 'ActualPremium'
        },
        {
            type: 'float',
            name: 'StampDuty'
        },
        {
            type: 'float',
            name: 'Discount'
        },
        {
            type: 'float',
            name: 'NetPremium'
        },
        {
            type: 'float',
            name: 'PaidPream'
        },
        {
            name: 'PolicyNo'
        },
        {
            type: 'date',
            name: 'ReceivedDate'
        },
        {
            type: 'date',
            name: 'PayDate'
        },
        {
            name: 'Remark'
        }
    ]
});