/*
 * File: app/model/Job.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.model.Job', {
    extend: 'Ext.data.Model',
    alias: 'model.job',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    idProperty: 'Id',

    fields: [
        {
            type: 'int',
            name: 'Id'
        },
        {
            type: 'string',
            name: 'Customer',
            mapping: 'Customer.NameEng'
        },
        {
            type: 'string',
            name: 'MarketingOfficer',
            mapping: 'MarketingOfficer.UsersAuthorize.UserId'
        },
        {
            type: 'string',
            name: 'LeadId'
        },
        {
            type: 'string',
            name: 'InformationId'
        },
        {
            type: 'string',
            name: 'IndicationId'
        },
        {
            type: 'string',
            name: 'ApplicationId'
        }
    ]
});