/*
 * File: app/view/Job/Application/Window/AdditionEquipmentDetail.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Job.Application.Window.AdditionEquipmentDetail', {
    extend: 'Ext.window.Window',
    alias: 'widget.jobapplicationwindowadditionequipmentdetail',

    requires: [
        'TabUserInformation.view.Job.Application.Window.AdditionEquipmentDetailViewModel',
        'TabUserInformation.view.Job.Application.Window.AdditionEquipmentDetailViewController',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.form.Label'
    ],

    controller: 'jobapplicationwindowadditionequipmentdetail',
    viewModel: {
        type: 'jobapplicationwindowadditionequipmentdetail'
    },
    title: 'Addition Equipment Detail',
    modal: true,

    listeners: {
        beforerender: 'onWindowBeforeRender'
    },
    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelWidth: 150,
                        labelAlign: 'right',
                        hideTrigger: true
                    },
                    title: 'Equipment 1',
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            width: 400,
                            fieldLabel: 'Equipment Name',
                            name: 'Equipment'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Equipment Cost',
                            name: 'CostBHT'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Deposit Cost',
                            name: 'Deposit'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Rental',
                            name: 'Rental'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'RV',
                            name: 'RVAmount'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'RV. %',
                            name: 'RV'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Net Rate Required',
                            name: 'IRRNet'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Financial Fee',
                            name: 'FinanceFeeAmount'
                        },
                        {
                            xtype: 'label',
                            colspan: 2,
                            text: 'Stilpulate Loss Value'
                        },
                        {
                            xtype: 'label',
                            text: '(a) At the commencement of Lease'
                        },
                        {
                            xtype: 'numberfield',
                            labelAlign: 'right',
                            name: 'CLPerUnit',
                            hideTrigger: true
                        },
                        {
                            xtype: 'label',
                            colspan: 3,
                            text: '(b) Monthly Diminishing Amount'
                        },
                        {
                            xtype: 'container',
                            layout: 'table',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: '(b) 1',
                                    labelAlign: 'right',
                                    labelWidth: 50,
                                    name: 'MDAmountFrom',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 80,
                                    fieldLabel: 'To',
                                    labelAlign: 'right',
                                    labelWidth: 30,
                                    name: 'MDAmountTo',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'label',
                                    colspan: 3,
                                    margin: '0 10 0 10',
                                    text: 'Month ='
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            labelAlign: 'right',
                            name: 'MDPerUnit',
                            hideTrigger: true
                        },
                        {
                            xtype: 'container',
                            layout: 'table',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: '(b) 2',
                                    labelAlign: 'right',
                                    labelWidth: 50,
                                    name: 'MDAmountFrom2',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 80,
                                    fieldLabel: 'To',
                                    labelAlign: 'right',
                                    labelWidth: 30,
                                    name: 'MDAmountTo2',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'label',
                                    colspan: 3,
                                    margin: '0 10 0 10',
                                    text: 'Month ='
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            labelAlign: 'right',
                            name: 'MDPerUnit2',
                            hideTrigger: true
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelWidth: 150,
                        labelAlign: 'right',
                        readOnly: true,
                        hideTrigger: true
                    },
                    title: 'Equipment 2',
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            width: 400,
                            fieldLabel: 'Equipment Name',
                            name: 'EquipmentName2'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Equipment Cost',
                            name: 'EquipmentCost2'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Deposit Cost',
                            name: 'DepositCost2'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Rental',
                            name: 'Rental2'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'RV',
                            name: 'RV2'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'RV. %',
                            name: 'RVPercent2'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Net Rate Required',
                            name: 'NetRateRequired2'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            fieldLabel: 'Financial Fee',
                            name: 'FinanceFeeAmount2'
                        },
                        {
                            xtype: 'label',
                            colspan: 2,
                            text: 'Stilpulate Loss Value'
                        },
                        {
                            xtype: 'label',
                            text: '(a) At the commencement of Lease'
                        },
                        {
                            xtype: 'numberfield',
                            labelAlign: 'right',
                            name: 'CLPerUnit2',
                            hideTrigger: true
                        },
                        {
                            xtype: 'label',
                            colspan: 3,
                            text: '(b) Monthly Diminishing Amount'
                        },
                        {
                            xtype: 'container',
                            layout: 'table',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: '(b) 1',
                                    labelAlign: 'right',
                                    labelWidth: 50,
                                    name: 'MDFrom2',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 80,
                                    fieldLabel: 'To',
                                    labelAlign: 'right',
                                    labelWidth: 30,
                                    name: 'MDTo2',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'label',
                                    colspan: 3,
                                    margin: '0 10 0 10',
                                    text: 'Month ='
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            labelAlign: 'right',
                            name: 'MDPerUnit2',
                            hideTrigger: true
                        },
                        {
                            xtype: 'container',
                            layout: 'table',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: '(b) 2',
                                    labelAlign: 'right',
                                    labelWidth: 50,
                                    name: 'MDFrom22',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 80,
                                    fieldLabel: 'To',
                                    labelAlign: 'right',
                                    labelWidth: 30,
                                    name: 'MDTo22',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'label',
                                    colspan: 3,
                                    margin: '0 10 0 10',
                                    text: 'Month ='
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            labelAlign: 'right',
                            name: 'MDPerUnit22',
                            hideTrigger: true
                        }
                    ]
                }
            ]
        }
    ]

});