/*
 * File: app/view/Job/Application/Window/BG.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Job.Application.Window.BG', {
    extend: 'Ext.window.Window',
    alias: 'widget.jobapplicationwindowbg',

    requires: [
        'TabUserInformation.view.Job.Application.Window.BGViewModel',
        'TabUserInformation.view.Job.Application.Window.BGViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    controller: 'jobapplicationwindowbg',
    viewModel: {
        type: 'jobapplicationwindowbg'
    },
    autoShow: true,
    height: 600,
    width: 800,
    title: 'BG',

    items: [
        {
            xtype: 'form',
            layout: 'auto',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'BG No',
                    labelAlign: 'right'
                }
            ],
            dockedItems: [
                {
                    xtype: 'gridpanel',
                    dock: 'bottom',
                    autoScroll: true,
                    manageHeight: false,
                    store: 'bGs',
                    listeners: {
                        itemdblclick: 'onGridpanelItemDblClick'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Id',
                            text: 'Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'BGNo',
                            text: 'BGNo'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ReceiveDate',
                            text: 'ReceiveDate'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'BGDate',
                            text: 'BGDate'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Bank',
                            text: 'Bank'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Branch',
                            text: 'Branch'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Amount',
                            text: 'Amount'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ContactNo',
                            text: 'ContactNo'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            ui: 'footer',
            width: 360,
            displayInfo: true,
            store: 'bGs'
        }
    ]

});