/*
 * File: app/view/Window/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.Window.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowloginwindow',

    requires: [
        'TabUserInformation.view.Window.LoginWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'windowloginwindow'
    },
    id: 'loginwindow',
    width: 400,
    bodyPadding: 30,
    closable: false,
    title: 'Commercial System Log-in',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    flex: 1,
                    id: 'username',
                    fieldLabel: 'Username'
                },
                {
                    xtype: 'textfield',
                    id: 'password',
                    fieldLabel: 'Password',
                    inputType: 'password'
                },
                {
                    xtype: 'button',
                    id: 'login',
                    text: 'Log-in',
                    listeners: {
                        click: 'onLoginClick'
                    }
                }
            ]
        }
    ],

    onLoginClick: function(button, e, eOpts) {
        var username = this.getComponent('username').getData();
        var password = this.getComponent('password').getData();
        console.log(username);

        var form = Ext.getCmp('loginwindow').getForm();
        if (form.isValid())
        {
            form.submit({
                url: url,
                success: function (form, action) {
                    window.location.href = "@Url.Action("Index", "Home")";
                },
                failure: function (form, action) {
                    Ext.Msg.alert('Failed', action.result ? action.result.message : 'No response');
                }
            });
        }
        else {
            Ext.Msg.alert('Data is not valid!', 'กรุณาเลือกข้อมูลให้ครบถ้วน');
        }
    }

});